config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  resources :enrollments
  
  get 'dashboard/index'

  controller :sessions do
    get     'login'   => :new
    post    'login'   => :create
    delete  'logout'  => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :users

  root 'dashboard#index', as: 'dashboard'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :enrollment

	validates :category, presence: true
	validates :name, presence: true
	validates :grade, presence: true
	validates :score, presence: true
	validates :max_score, presence: true

  validates_numericality_of :max_score, greater_than_or_equal_to: :score
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_enrollment_id, only: [:index, :show, :new, :edit]
  before_action :set_categories
  before_action :set_grades

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where(enrollment_id: params[:enrollment_id])
    @course = @enrollment.course
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @enrollment = Enrollment.find(task_params[:enrollment_id])
    @task = @enrollment.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path(enrollment_id: @enrollment.id), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, locals: { enrollment_id: @enrollment.id } }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @enrollment = Enrollment.find(task_params[:enrollment_id])

    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path(enrollment_id: @enrollment.id), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_grades
      @grades = [["Select one", ""], "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F"]
    end

    def set_categories
      @categories = [["Select one", ""], "Homework", "Project", "Midterm", "Final Exam"]
    end

    def set_enrollment_id
      @enrollment = Enrollment.find(params[:enrollment_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:enrollment_id, :category, :name, :score, :max_score, :is_submitted, :grade)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for @task, html: {class: 'form-detail'} do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.select :category, @categories, {}, {class: 'form-control'}  %>
  </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :is_submitted %><br>
    <%= f.check_box :is_submitted %>
  </div>

  <div class="form-group">
    <%= f.label :score %><br>
    <%= f.text_field :score, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :max_score %><br>
    <%= f.text_field :max_score, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :grade %><br>
    <%= f.select :grade, @grades, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :enrollment_id, value: @enrollment.id %>

  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path(enrollment_id: @enrollment.id), {class: 'btn btn-default'} %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course Tasks for <%= @course.name %></h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="1">Category</th>
        <th colspan="1">Name</th>
        <th colspan="1">Is Submitted?</th>
        <th colspan="1">Score</th>
        <th colspan="1">Max Score</th>
        <th colspan="1">Grade</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.category %></td>
          <td><%= task.name %></td>
          <td><%= task.is_submitted %></td>
          <td><%= task.score %></td>
          <td><%= task.max_score %></td>
          <td><%= task.grade %></td>
          <td><%= link_to 'Edit', edit_task_path(task, enrollment_id: @enrollment.id) %></td>
          <td><% link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      <% if !@tasks.empty? %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td><%= @enrollment.total_score %></td>
          <td><%= @enrollment.total_max_score %></td>
          <td><%= @enrollment.total_percentage.to_s + '%' %></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Task', new_task_path(enrollment_id: @enrollment.id), { class: 'btn btn-default' }  %>
<%= link_to 'Back', dashboard_url, { class: 'btn btn-default' }  %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path(enrollment_id: @enrollment.id), {class: 'btn btn-default'} %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_path(@task, enrollment_id: @enrollment.id) %> |
<%= link_to 'Back', tasks_path(enrollment_id: @enrollment.id) %>