config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  resources :enrollments
  
  get 'dashboard/index'

  controller :sessions do
    get     'login'   => :new
    post    'login'   => :create
    delete  'logout'  => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :users

  root 'dashboard#index', as: 'dashboard'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :student

  validates :name, presence: true, uniqueness: true, length: { minimum: 4 }
  
  accepts_nested_attributes_for :student

  after_destroy :ensure_a_user_remains
  has_secure_password

  private

    def ensure_a_user_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  skip_before_action :authorize, only: [:new, :create, :show]
  before_action :already_signed_in, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @user.build_student
    @user.student.build_address
    2.times { @user.student.parents.build }
  end

  # GET /users/1/edit
  def edit

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    puts @user.student

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name, 
        :password, 
        :password_confirmation, 
        student_attributes: [
          :id,
          :first_name, 
          :last_name, 
          :grade, 
          :home_phone_number, 
          :cell_phone_number, 
          :email,
          address_attributes: [
            :id,
            :street,
            :city,
            :state,
            :zip
          ],
          parents_attributes: [
            :id,
            :first_name,
            :last_name,
            :occupation
          ]
        ]
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_address_form.html.erb
  <h2>Address Information</h2>

<%= f.fields_for :address do |f_address| %>

  <div class="form-group">
    <%= f_address.label :street %><br>
    <%= f_address.text_field :street, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f_address.label :city %><br>
    <%= f_address.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f_address.label :state %><br>
    <%= f_address.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f_address.label :zip %><br>
    <%= f_address.text_field :zip, class: "form-control" %>
  </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for @user, url: {action: "create"}, html: {class: 'form-signup'} do |f_user| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Account Information</h2>

  <div class="form-group">
    <%= f_user.label :name %><br>
    <%= f_user.text_field :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f_user.label :password %><br>
    <%= f_user.password_field :password, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f_user.label :password_confirmation %><br>
    <%= f_user.password_field :password_confirmation, class: "form-control"  %>
  </div>

  <%= render partial: 'student_form', locals: { f: f_user } %>

  <div class="actions">
    <%= f_user.submit  class: 'btn btn-default' %>
  </div>

<% end %>

app/views/users/_parent_form.html.erb
<h2>Parent Information</h2>

<%= f.fields_for :parents do |f_parent| %>
  <div class="form-group">
    <%= f_parent.label :first_name %><br>
    <%= f_parent.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f_parent.label :last_name %><br>
    <%= f_parent.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f_parent.label :occupation %><br>
    <%= f_parent.text_field :occupation, class: "form-control" %>
  </div>
<% end %>

app/views/users/_student_form.html.erb
<h2>Student Information</h2>

<%= f.fields_for :student do |f_student| %>

  <div class="form-group">
    <%= f_student.label :first_name %><br>
    <%= f_student.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f_student.label :last_name %><br>
    <%= f_student.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f_student.label :grade %><br>
    <%= f_student.text_field :grade, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f_student.label :email %><br>
    <%= f_student.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f_student.label :home_phone_number %><br>
    <%= f_student.text_field :home_phone_number, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f_student.label :cell_phone_number %><br>
    <%= f_student.text_field :cell_phone_number, class: "form-control" %>
  </div>

  <%= render partial: 'parent_form', locals: { f: f_student } %>

  <%= render partial: 'address_form', locals: { f: f_student } %>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<p id="notice"><%= notice %></p>

<%= form_for @user, url: {action: "update"}, html: {class: 'form-signup'} do |f_user| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Account Information</h2>

  <div class="form-group">
    <%= f_user.label :name %><br>
    <%= f_user.text_field :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f_user.label :password %><br>
    <%= f_user.password_field :password, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f_user.label :password_confirmation %><br>
    <%= f_user.password_field :password_confirmation, class: "form-control"  %>
  </div>

  <%= render partial: 'student_form', locals: { f: f_user } %>

  <div class="actions">
    <%= f_user.submit  class: 'btn btn-default' %>
  </div>

<% end %>


<%= link_to 'Back', @user, {class: 'btn btn-default'} %>
<%# link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3>User Information</h3>

<p>
  <strong>Username:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.student.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.student.last_name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @user.student.grade %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.student.email %>
</p>

<p>
  <strong>Home phone number:</strong>
  <%= @user.student.home_phone_number %>
</p>

<p>
  <strong>Cell phone number:</strong>
  <%= @user.student.cell_phone_number %>
</p>

<h3>Parent Information</h3>

<% @user.student.parents.each do |parent| %>
	<p>
	  <strong>First Name</strong>
	  <%= parent.first_name %>
	</p>

	<p>
	  <strong>Last Name</strong>
	  <%= parent.last_name %>
	</p>

	<p>
	  <strong>Occupation</strong>
	  <%= parent.occupation %>
	</p>

<% end %>

<h3>Address Information</h3>

<% if !@user.student.address.nil? %>
  <p>
    <strong>Street</strong>
    <%= @user.student.address.street %>
  </p>

  <p>
    <strong>City</strong>
    <%= @user.student.address.city %>
  </p>

  <p>
    <strong>State</strong>
    <%= @user.student.address.state %>
  </p>

  <p>
    <strong>zip</strong>
    <%= @user.student.address.zip %>
  </p>
<% end %>

<%= link_to 'Edit', edit_user_path(@user), {class: 'btn btn-default'} %>

<%= link_to 'Back', dashboard_url, {class: 'btn btn-default'} %>