config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  resources :enrollments
  
  get 'dashboard/index'

  controller :sessions do
    get     'login'   => :new
    post    'login'   => :create
    delete  'logout'  => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :users

  root 'dashboard#index', as: 'dashboard'

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :course
	belongs_to :student
	has_many :tasks

	def total_score
		return tasks.to_a.sum {|task| task.score}
	end

	def total_max_score
		return tasks.to_a.sum {|task| task.max_score}
	end

	def total_percentage
		if total_score().to_f <= 0 || total_max_score().to_f <= 0
			return "100.0"
		end

		return ((total_score().to_f / total_max_score().to_f) * 100.00).round(2)
	end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Student.find(session[:user_id]).enrollments
    @courses = Course.all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    course = Course.find(params[:course_id])
    student = Student.find_by(user_id: session[:user_id])
    enrollment = Enrollment.find_by(course_id: course.id, student_id: student.id)

    if enrollment.nil?
      enrollment = student.enrollments.build(course_id: course.id)      
    end

    respond_to do |format|
      if enrollment.save
        @enrollments = Student.find_by(user_id: session[:user_id]).enrollments
        #format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.js { enrollments = @enrollments }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params[:course_id]
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollments.html.erb
<h2>Currently Enrolled</h2>

<div class="table-responsive">
    <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="1">Course Number</th>
        <th colspan="1">Course Name</th>
        <th colspan="1">Final Grade</th>
        <th colspan="1"></th>
        <th colspan="1"></th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @enrollments.each do |enrollment| %>
        <tr>
          <td><%= enrollment.course.course_number %></td>
          <td><%= enrollment.course.name %></td>
          <td><%= enrollment.grade.nil? ? "In progress" : enrollment.grade %></td>
          <td><%# link_to 'Show', enrollment %></td>
          <td><%# link_to 'Edit', edit_enrollment_path(enrollment) %></td>
          <td><%= button_to 'Remove Course', enrollment, class: 'btn btn-default',method: :delete, data: { confirm: 'Are you sure? Removing this course from your enrollment will also delete the associated tasks.' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/enrollments/create.js.erb
$('#notice').hide();

$('div#current_enrollments').html("<%= escape_javascript render 'enrollments' %>");

app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<div class="table-responsive">
    <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="1">Course Number</th>
        <th colspan="1">Course Name</th>
        <th colspan="1">Course Description</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.course_number %></td>
          <td><%= course.name %></td>
          <td><%= course.description %></td>
          <td><%= button_to 'Add Course', enrollments_path(course_id: course), class: 'btn btn-default', method: :post, remote: true %></td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

<div id="current_enrollments">
  <%= render 'enrollments', enrollments: @enrollments %>
</div>

<br>

<%# link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grade</strong>
  <%= @enrollment.grade.nil? ? "In progress" : @enrollment.grade %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>