config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  resources :enrollments
  
  get 'dashboard/index'

  controller :sessions do
    get     'login'   => :new
    post    'login'   => :create
    delete  'logout'  => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :users

  root 'dashboard#index', as: 'dashboard'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bvcs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container-fluid">
	  	
	    <div class="navbar-header">
	    	<% if session[:user_id] %>
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
	      <% end %>
	      <a class="navbar-brand" href="/">BVCS School Portal</a>
	    </div>
	    <% if session[:user_id] %>
	    <div id="navbar" class="navbar-collapse collapse">
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to 'Home', dashboard_path %></li>
	        <li><%= link_to 'Register', enrollments_path %></li>
	        <li><%= link_to 'Account Settings', user_path(session[:user_id]) %></li>
	        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
	      </ul>
	    </div>
	    <% end %>
	  </div>
	</nav>

	<div class="container-fluid">
		<div class="col-sm-12 col-md-12 main">
    	<%= yield %>
    </div>
	</div>

</body>
</html>